export const FETCH_PIZZAS = 'FETCH_PIZZAS';

export const FETCH_CURRENCY = 'FETCH_CURRENCY';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const INCREACE_ITEM_QUANTITY = 'INCREACE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const CLEAR_ALL_CART_ITEMS = 'CLEAR_ALL_CART_ITEMS';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const POST_ORDER = 'POST_ORDER';
